# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: install home-assistant in venv
  pip:
    name: homeassistant
    virtualenv: "{{ ha_venv }}"
    virtualenv_command: pyvenv-3.5

- name: install colorlog
  pip:
    name: colorlog
    virtualenv: "{{ ha_venv }}"

