# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: install home-assistant
  pip:
    name: homeassistant

- name: install colorlog
  pip:
    name: colorlog

