# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- name: install apt packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - bluez
    - libffi-dev
    - libssl-dev
    - libjpeg-dev
    - zlib1g-dev
    - autoconf
    - build-essential
    - libopenjp2-7
    - libtiff5
    - libturbojpeg0-dev
    - tzdata
    - ffmpeg
    - liblapack3
    - liblapack-dev
    - libatlas-base-dev

- name: install debian-required pip packages
  pip:
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - appdirs
    - packaging
  when: ansible_distribution == "Debian"

- name: create user
  user:
    name: "{{ ha_user }}"
    comment: "Home Assistant"
    system: yes
    shell: "/sbin/nologin"
    groups: dialout
    append: yes

- name: create directory
  file:
    path: "{{ ha_conf_dir }}"
    state: directory
    mode: 02775
    owner: "{{ ha_user }}"
    group: "{{ ha_user }}"

- name: create venv
  command:
    cmd: python3 -m venv /opt/venv_ha

- name: change owner of venv dir
  file:
    path: /opt/venv_ha
    owner: ha
    group: ha
    state: directory
    recurse: yes

- name: install wheel in venv
  pip:
    virtualenv: /opt/venv_ha
    virtualenv_python: python3
    name: wheel

