# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2016 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under MIT. All rights reserved.
#
---
- name: install python and dependencies for ansible modules
  raw: dnf -y install python2 python2-dnf libselinux-python firewalld
  changed_when: false

- name: install required packages
  package: name={{ item }} state=present
  with_items:
  - python3-pip
  - python-firewall
  - python3-devel
  - gcc


- name: create user
  user: name={{ ha_user }} comment="Home Assistant" createhome=no system=yes shell="/sbin/nologin"

- name: create directory
  file: path={{ ha_conf_dir }} state=directory mode=0755 owner={{ ha_user }} group={{ ha_user }}

