# This file is part of the Home Assistant role.
#
# Copyright (c) 2015-2020 Fabian Affolter <fabian@affolter-engineering.ch>
#
# Licensed under Apache 2.0. All rights reserved.
#
---
- shell: which /opt/venv_ha/bin/hass
  register: hass_command
  # TODO refactor clearly this is no longer needed

- name: install systemd unit file
  template:
    src: home-assistant.service.j2
    dest: "/etc/systemd/system/home-assistant.service"
    owner: root
    group: root
    mode: 0644

- name: start home assistant
  systemd:
    name: home-assistant
    daemon_reload: yes
    enabled: yes
    state: started
